# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
#,,Hot water program,,,,,,,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,

#10 17
r,,WP.Mo.1,Hot water program Mo 1 Start/End (User 151) ,,,,"101702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Mo.1,Hot water program Mo 1 Start/End (User 151) ,,,,"1017",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#11 17
r,,WP.Mo.2,Hot water program Mo 2 Start/End (User 151) ,,,,"111702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Mo.2,Hot water program Mo 2 Start/End (User 151) ,,,,"1117",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#12 17
r,,WP.Mo.3,Hot water program Mo 3 Start/End (User 151) ,,,,"121702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Mo.3,Hot water program Mo 3 Start/End (User 151) ,,,,"1217",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#20 17
r,,WP.Tu.1,Hot water program Tu 1 Start/End (User 152) ,,,,"201702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Tu.1,Hot water program Tu 1 Start/End (User 152) ,,,,"2017",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#21 17
r,,WP.Tu.2,Hot water program Tu 2 Start/End (User 152) ,,,,"211702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Tu.2,Hot water program Tu 2 Start/End (User 152) ,,,,"2117",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#22 17
r,,WP.Tu.3,Hot water program Tu 3 Start/End (User 152) ,,,,"221702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Tu.3,Hot water program Tu 3 Start/End (User 152) ,,,,"2217",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#30 17
r,,WP.We.1,Hot water program We 1 Start/End (User 153) ,,,,"301702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.We.1,Hot water program We 1 Start/End (User 153) ,,,,"3017",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#31 17
r,,WP.We.2,Hot water program We 2 Start/End (User 153) ,,,,"311702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.We.2,Hot water program We 2 Start/End (User 153) ,,,,"3117",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#32 17
r,,WP.We.3,Hot water program We 3 Start/End (User 153) ,,,,"321702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.We.3,Hot water program We 3 Start/End (User 153) ,,,,"3217",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#40 17
r,,WP.Th.1,Hot water program Th 1 Start/End (User 154) ,,,,"401702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Th.1,Hot water program Th 1 Start/End (User 154) ,,,,"4017",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#41 17
r,,WP.Th.2,Hot water program Th 2 Start/End (User 154) ,,,,"411702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Th.2,Hot water program Th 2 Start/End (User 154) ,,,,"4117",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#42 17
r,,WP.Th.3,Hot water program Th 3 Start/End (User 154) ,,,,"421702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Th.3,Hot water program Th 3 Start/End (User 154) ,,,,"4217",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#50 17
r,,WP.Fr.1,Hot water program Fr 1 Start/End (User 155) ,,,,"501702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Fr.1,Hot water program Fr 1 Start/End (User 155) ,,,,"5017",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#51 17
r,,WP.Fr.2,Hot water program Fr 2 Start/End (User 155) ,,,,"511702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Fr.2,Hot water program Fr 2 Start/End (User 155) ,,,,"5117",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#52 17
r,,WP.Fr.3,Hot water program Fr 3 Start/End (User 155) ,,,,"521702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Fr.3,Hot water program Fr 3 Start/End (User 155) ,,,,"5217",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#60 17
r,,WP.Sa.1,Hot water program Sa 1 Start/End (User 156) ,,,,"601702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Sa.1,Hot water program Sa 1 Start/End (User 156) ,,,,"6017",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#61 17
r,,WP.Sa.2,Hot water program Sa 2 Start/End (User 156) ,,,,"611702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Sa.2,Hot water program Sa 2 Start/End (User 156) ,,,,"6117",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#62 17
r,,WP.Sa.3,Hot water program Sa 3 Start/End (User 156) ,,,,"621702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Sa.3,Hot water program Sa 3 Start/End (User 156) ,,,,"6217",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#70 17
r,,WP.Su.1,Hot water program Su 1 Start/End (User 157) ,,,,"701702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Su.1,Hot water program Su 1 Start/End (User 157) ,,,,"7017",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#71 17
r,,WP.Su.2,Hot water program Su 2 Start/End (User 157) ,,,,"711702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Su.2,Hot water program Su 2 Start/End (User 157) ,,,,"7117",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#72 17
r,,WP.Su.3,Hot water program Su 3 Start/End (User 157) ,,,,"721702",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,WP.Su.3,Hot water program Su 3 Start/End (User 157) ,,,,"7217",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,