# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
#,,Process values ​​heating Circuit controller,,,,,,,,,,,,
*u,,,,,,"5014",,,,,,,
*uw,,,,,,"5014",,,,,,,

u,,HcMode,Exch values ,,,,,Opmodeskip,,_8_Skip,,, ,Pump,,BI0,0=Off;1=On,, ,ValveOpening,,BI1,0=Off;1=On,, ,ValveClosing,,BI2,0=Off;1=On,, ,Opmode_4,,BI3,,, ,Opmode_5,,BI4,,, ,Opmode_6,,BI5,,, ,Opmode_7,,BI6,,, ,Opmode_8,,BI7,,, ,SupplyHCTemp,,_16_Temp0,,, ,Temp3,,_8_Skip,,, ,Status,,UCH,,, ,BoilerMCBoostTemp,,_8_Temp2K,,, ,SupplyMaxTemp,,_8_Temp2,,, ,SupplyMinTemp,,_8_Temp2,,, ,
#uw,,HcModew,Exch values ,,,,,Opmode1,,UCH,,, ,Temp1,,_16_Temp0,,, ,Temp2,,_8_Temp2,,, ,Temp5,,_8_Temp2,,, ,Opmode2,,UCH,,, ,s,,_8_Skip,,, ,
