# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
#,,Process values ​​heating Circuit controller,,,,,,,,,,,,
*u,,,,,,"5014",,,,,,,
*uw,,,,,,"5014",,,,,,,

u,,HcMode,Exch values ,,,,,Opmode3,,_8_Opdataheat,,, ,Temp3,,_16_Temp0,,, ,Temp4,,_16_Temp0,,, ,BoilerMCBoostTemp2,,_8_Temp2,,, ,SupplyMaxTemp2,,_8_Temp2,,, ,SupplyMinTemp2,,_8_Temp2,,, ,
#uw,,HcMode,Exch values ,,,,,Opmode1,,_8_Opdataheat,,, ,Temp1,,_16_Temp0,,, ,Temp2,,_16_Temp0,,, ,Opmode2,,_8_Opdataheat,,, ,s,,_8_Skip,,, ,Opmode3,,_8_Opdataheat,,, ,