# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
#,,Process values ​​heating circuit controller,,,,,,,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,

#73 09
r,,Unknown3, ,,,,"730902",Unknown2,,_16_Temp10,,,
w,,Unknown3, ,,,,"7309",Unknown2,,_16_Temp10,,,

#81 09
r,,Unknown5, ,,,,"B10902",Unknown5,,_16_Temp10,,,
w,,Unknown5, ,,,,"B109",Unknown5,,_16_Temp10,,,
