# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
#,,HP2 Heating Program,,,,,,,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,

#10 15
r,,HP2.Mo.1,Heating Program 2 Mo 1 Start/End (User 131) ,,,,"101502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Mo.1,Heating Program 2 Mo 1 Start/End (User 131) ,,,,"1015",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#11 15
r,,HP2.Mo.2,Heating Program 2 Mo 2 Start/End (User 131) ,,,,"111502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Mo.2,Heating Program 2 Mo 2 Start/End (User 131) ,,,,"1115",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#12 15
r,,HP2.Mo.3,Heating Program 2 Mo 3 Start/End (User 131) ,,,,"121502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Mo.3,Heating Program 2 Mo 3 Start/End (User 131) ,,,,"1215",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#20 15
r,,HP2.Tu.1,Heating Program 2 Tu 1 Start/End (User 132) ,,,,"201502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Tu.1,Heating Program 2 Tu 1 Start/End (User 132) ,,,,"2015",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#21 15
r,,HP2.Tu.2,Heating Program 2 Tu 2 Start/End (User 132) ,,,,"211502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Tu.2,Heating Program 2 Tu 2 Start/End (User 132) ,,,,"2115",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#22 15
r,,HP2.Tu.3,Heating Program 2 Tu 3 Start/End (User 132) ,,,,"221502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Tu.3,Heating Program 2 Tu 3 Start/End (User 132) ,,,,"2215",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#30 15
r,,HP2.We.1,Heating Program 2 We 1 Start/End (User 133) ,,,,"301502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.We.1,Heating Program 2 We 1 Start/End (User 133) ,,,,"3015",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#31 15
r,,HP2.We.2,Heating Program 2 We 2 Start/End (User 133) ,,,,"311502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.We.2,Heating Program 2 We 2 Start/End (User 133) ,,,,"3115",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#32 15
r,,HP2.We.3,Heating Program 2 We 3 Start/End (User 133) ,,,,"321502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.We.3,Heating Program 2 We 3 Start/End (User 133) ,,,,"3215",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#40 15
r,,HP2.Th.1,Heating Program 2 Th 1 Start/End (User 134) ,,,,"401502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Th.1,Heating Program 2 Th 1 Start/End (User 134) ,,,,"4015",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#41 15
r,,HP2.Th.2,Heating Program 2 Th 2 Start/End (User 134) ,,,,"411502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Th.2,Heating Program 2 Th 2 Start/End (User 134) ,,,,"4115",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#42 15
r,,HP2.Th.3,Heating Program 2 Th 3 Start/End (User 134) ,,,,"421502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Th.3,Heating Program 2 Th 3 Start/End (User 134) ,,,,"4215",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#50 15
r,,HP2.Fr.1,Heating Program 2 Fr 1 Start/End (User 135) ,,,,"501502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Fr.1,Heating Program 2 Fr 1 Start/End (User 135) ,,,,"5015",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#51 15
r,,HP2.Fr.2,Heating Program 2 Fr 2 Start/End (User 135) ,,,,"511502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Fr.2,Heating Program 2 Fr 2 Start/End (User 135) ,,,,"5115",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#51 15
r,,HP2.Fr.3,Heating Program 2 Fr 3 Start/End (User 135) ,,,,"521502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Fr.3,Heating Program 2 Fr 3 Start/End (User 135) ,,,,"5215",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#60 15
r,,HP2.Sa.1,Heating Program 2 Sa 1 Start/End (User 136) ,,,,"601502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Sa.1,Heating Program 2 Sa 1 Start/End (User 136) ,,,,"6015",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#61 15
r,,HP2.Sa.2,Heating Program 2 Sa 2 Start/End (User 136) ,,,,"611502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Sa.2,Heating Program 2 Sa 2 Start/End (User 136) ,,,,"6115",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#62 15
r,,HP2.Sa.3,Heating Program 2 Sa 3 Start/End (User 136) ,,,,"621502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Sa.3,Heating Program 2 Sa 3 Start/End (User 136) ,,,,"6215",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#70 15
r,,HP2.Su.1,Heating Program 2 Su 1 Start/End (User 137) ,,,,"701502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Su.1,Heating Program 2 Su 1 Start/End (User 137) ,,,,"7015",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#71 15
r,,HP2.Su.2,Heating Program 2 Su 2 Start/End (User 137) ,,,,"711502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Su.2,Heating Program 2 Su 2 Start/End (User 137) ,,,,"7115",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#72 15
r,,HP2.Su.3,Heating Program 2 Su 3 Start/End (User 137) ,,,,"721502",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP2.Su.3,Heating Program 2 Su 3 Start/End (User 137) ,,,,"7215",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,


### 16
#10 16
r,,HP3.Mo.1,Heating Program 3 Mo 1 Start/End (User 141) ,,,,"101602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Mo.1,Heating Program 3 Mo 1 Start/End (User 141) ,,,,"1016",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#11 16
r,,HP3.Mo.2,Heating Program 3 Mo 2 Start/End (User 141) ,,,,"111602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Mo.2,Heating Program 3 Mo 2 Start/End (User 141) ,,,,"1116",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#12 16
r,,HP3.Mo.3,Heating Program 3 Mo 3 Start/End (User 141) ,,,,"121602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Mo.3,Heating Program 3 Mo 3 Start/End (User 141) ,,,,"1216",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#20 16
r,,HP3.Tu.1,Heating Program 3 Tu 1 Start/End (User 142) ,,,,"201602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Tu.1,Heating Program 3 Tu 1 Start/End (User 142) ,,,,"2016",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#21 16 
r,,HP3.Tu.2,Heating Program 3 Tu 2 Start/End (User 142) ,,,,"211602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Tu.2,Heating Program 3 Tu 2 Start/End (User 142) ,,,,"2116",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#22 16
r,,HP3.Tu.3,Heating Program 3 Tu 3 Start/End (User 142) ,,,,"221602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Tu.3,Heating Program 3 Tu 3 Start/End (User 142) ,,,,"2216",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#30 16
r,,HP3.We.1,Heating Program 3 We 1 Start/End (User 143) ,,,,"301602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.We.1,Heating Program 3 We 1 Start/End (User 143) ,,,,"3016",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#31 16
r,,HP3.We.2,Heating Program 3 We 2 Start/End (User 143) ,,,,"311602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.We.2,Heating Program 3 We 2 Start/End (User 143) ,,,,"3116",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#32 16
r,,HP3.We.3,Heating Program 3 We 3 Start/End (User 143) ,,,,"321602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.We.3,Heating Program 3 We 3 Start/End (User 143) ,,,,"3216",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#40 16
r,,HP3.Th.1,Heating Program 3 Th 1 Start/End (User 144) ,,,,"401602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Th.1,Heating Program 3 Th 1 Start/End (User 144) ,,,,"4016",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#41 16
r,,HP3.Th.2,Heating Program 3 Th 2 Start/End (User 144) ,,,,"411602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Th.2,Heating Program 3 Th 2 Start/End (User 144) ,,,,"4116",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#42 16
r,,HP3.Th.3,Heating Program 3 Th 3 Start/End (User 144) ,,,,"421602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Th.3,Heating Program 3 Th 3 Start/End (User 144) ,,,,"4216",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#50 16
r,,HP3.Fr.1,Heating Program 3 Fr 1 Start/End (User 145) ,,,,"501602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Fr.1,Heating Program 3 Fr 1 Start/End (User 145) ,,,,"5016",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#51 16
r,,HP3.Fr.2,Heating Program 3 Fr 2 Start/End (User 145) ,,,,"511602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Fr.2,Heating Program 3 Fr 2 Start/End (User 145) ,,,,"5116",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#52 16
r,,HP3.Fr.3,Heating Program 3 Fr 3 Start/End (User 145) ,,,,"521602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Fr.3,Heating Program 3 Fr 3 Start/End (User 145) ,,,,"5216",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#60 16
r,,HP3.Sa.1,Heating Program 3 Sa 1 Start/End (User 146) ,,,,"601602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Sa.1,Heating Program 3 Sa 1 Start/End (User 146) ,,,,"6016",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#61 16
r,,HP3.Sa.2,Heating Program 3 Sa 2 Start/End (User 146) ,,,,"611602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Sa.2,Heating Program 3 Sa 2 Start/End (User 146) ,,,,"6116",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#62 16
r,,HP3.Sa.3,Heating Program 3 Sa 3 Start/End (User 146) ,,,,"621602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Sa.3,Heating Program 3 Sa 3 Start/End (User 146) ,,,,"6216",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#70 16
r,,HP3.Su.1,Heating Program 3 Su 1 Start/End (User 147) ,,,,"701602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Su.1,Heating Program 3 Su 1 Start/End (User 147) ,,,,"7016",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#71 16
r,,HP3.Su.2,Heating Program 3 Su 2 Start/End (User 147) ,,,,"711602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Su.2,Heating Program 3 Su 2 Start/End (User 147) ,,,,"7116",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#72 16
r,,HP3.Su.3,Heating Program 3 Su 3 Start/End (User 147) ,,,,"721602",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP3.Su.3,Heating Program 3 Su 3 Start/End (User 147) ,,,,"7216",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
