# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
#,,Program Calendar Circulation ,,,,,,,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,

#10 1A
r,,ZP.Mo.1,Circulation program Mo 1 Start/End (User 161) ,,,,"101A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Mo.1,Circulation program Mo 1 Start/End (User 161) ,,,,"101A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#11 1A
r,,ZP.Mo.2,Circulation program Mo 2 Start/End (User 161) ,,,,"111A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Mo.2,Circulation program Mo 2 Start/End (User 161) ,,,,"111A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#12 1A
r,,ZP.Mo.3,Circulation program Mo 3 Start/End (User 161) ,,,,"121A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Mo.3,Circulation program Mo 3 Start/End (User 161) ,,,,"121A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#20 1A
r,,ZP.Tu.1,Circulation program Tu 1 Start/End (User 162) ,,,,"201A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Tu.1,Circulation program Tu 1 Start/End (User 162) ,,,,"201A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#21 1A
r,,ZP.Tu.2,Circulation program Tu 2 Start/End (User 162) ,,,,"211A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Tu.2,Circulation program Tu 2 Start/End (User 162) ,,,,"211A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#22 1A
r,,ZP.Tu.3,Circulation program Tu 3 Start/End (User 162) ,,,,"221A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Tu.3,Circulation program Tu 3 Start/End (User 162) ,,,,"221A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#30 1A
r,,ZP.We.1,Circulation program We 1 Start/End (User 163) ,,,,"301A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.We.1,Circulation program We 1 Start/End (User 163) ,,,,"301A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#31 1A
r,,ZP.We.2,Circulation program We 2 Start/End (User 163) ,,,,"311A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.We.2,Circulation program We 2 Start/End (User 163) ,,,,"311A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#31 1A
r,,ZP.We.3,Circulation program We 3 Start/End (User 163) ,,,,"321A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.We.3,Circulation program We 3 Start/End (User 163) ,,,,"321A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#40 1A
r,,ZP.Th.1,Circulation program Th 1 Start/End (User 164) ,,,,"401A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Th.1,Circulation program Th 1 Start/End (User 164) ,,,,"401A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#41 1A
r,,ZP.Th.2,Circulation program Th 2 Start/End (User 164) ,,,,"411A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Th.2,Circulation program Th 2 Start/End (User 164) ,,,,"411A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#42 1A
r,,ZP.Th.3,Circulation program Th 3 Start/End (User 164) ,,,,"421A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Th.3,Circulation program Th 3 Start/End (User 164) ,,,,"421A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#50 1A
r,,ZP.Fr.1,Circulation program Fr 1 Start/End (User 165) ,,,,"501A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Fr.1,Circulation program Fr 1 Start/End (User 165) ,,,,"501A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#51 1A
r,,ZP.Fr.2,Circulation program Fr 2 Start/End (User 165) ,,,,"511A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Fr.2,Circulation program Fr 2 Start/End (User 165) ,,,,"511A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#52 1A
r,,ZP.Fr.3,Circulation program Fr 3 Start/End (User 165) ,,,,"521A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Fr.3,Circulation program Fr 3 Start/End (User 165) ,,,,"521A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#60 1A
r,,ZP.Sa.1,Circulation program Sa 1 Start/End (User 166) ,,,,"601A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Sa.1,Circulation program Sa 1 Start/End (User 166) ,,,,"601A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#61 1A
r,,ZP.Sa.2,Circulation program Sa 2 Start/End (User 166) ,,,,"611A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Sa.2,Circulation program Sa 2 Start/End (User 166) ,,,,"611A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#62 1A
r,,ZP.Sa.3,Circulation program Sa 3 Start/End (User 166) ,,,,"621A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Sa.3,Circulation program Sa 3 Start/End (User 166) ,,,,"621A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#70 1A
r,,ZP.Su.1,Circulation program Su 1 Start/End (User 167) ,,,,"701A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Su.1,Circulation program Su 1 Start/End (User 167) ,,,,"701A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#71 1A
r,,ZP.Su.2,Circulation program Su 2 Start/End (User 167) ,,,,"711A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Su.2,Circulation program Su 2 Start/End (User 167) ,,,,"711A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#72 1A
r,,ZP.Su.3,Circulation program Su 3 Start/End (User 167) ,,,,"721A02",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,ZP.Su.3,Circulation program Su 3 Start/End (User 167) ,,,,"721A",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,