# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
#,,Process values ​​heating circuit controller,,,,,,,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,

#10 14
r,,HP1.Mo.1,Heating program 1 Mo 1 Start/End (User 121) ,,,,"101402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Mo.1,Heating program 1 Mo 1 Start/End (User 121) ,,,,"1014",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#11 14
r,,HP1.Mo.2,Heating program 1 Mo 2 Start/End (User 121) ,,,,"111402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Mo.2,Heating program 1 Mo 2 Start/End (User 121) ,,,,"1114",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#12 14
r,,HP1.Mo.3,Heating program 1 Mo 3 Start/End (User 121) ,,,,"121402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Mo.3,Heating program 1 Mo 3 Start/End (User 121) ,,,,"1214",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#20 14
r,,HP1.Tu.1,Heating program 1 Tu 1 Start/End (User 122) ,,,,"201402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Tu.1,Heating program 1 Tu 1 Start/End (User 122) ,,,,"2014",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#21 14
r,,HP1.Tu.2,Heating program 1 Tu 2 Start/End (User 122) ,,,,"211402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Tu.2,Heating program 1 Tu 2 Start/End (User 122) ,,,,"2114",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#22 14
r,,HP1.Tu.3,Heating program 1 Tu 3 Start/End (User 122) ,,,,"221402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Tu.3,Heating program 1 Tu 3 Start/End (User 122) ,,,,"2214",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#30 14
r,,HP1.We.1,Heating program 1 We 1 Start/End (User 123) ,,,,"301402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.We.1,Heating program 1 We 1 Start/End (User 123) ,,,,"3014",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#31 14
r,,HP1.We.2,Heating program 1 We 2 Start/End (User 123) ,,,,"311402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.We.2,Heating program 1 We 2 Start/End (User 123) ,,,,"3114",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#32 14
r,,HP1.We.3,Heating program 1 We 3 Start/End (User 123) ,,,,"321402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.We.3,Heating program 1 We 3 Start/End (User 123) ,,,,"3214",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#40 14
r,,HP1.Th.1,Heating program 1 Th 1 Start/End (User 124) ,,,,"401402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Th.1,Heating program 1 Th 1 Start/End (User 124) ,,,,"4014",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#41 14
r,,HP1.Th.2,Heating program 1 Th 2 Start/End (User 124) ,,,,"411402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Th.2,Heating program 1 Th 2 Start/End (User 124) ,,,,"4114",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#42 14
r,,HP1.Th.3,Heating program 1 Th 3 Start/End (User 124) ,,,,"421402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Th.3,Heating program 1 Th 3 Start/End (User 124) ,,,,"4214",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#50 14
r,,HP1.Fr.1,Heating program 1 Fr 1 Start/End (User 125) ,,,,"501402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Fr.1,Heating program 1 Fr 1 Start/End (User 125) ,,,,"5014",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#51 14
r,,HP1.Fr.2,Heating program 1 Fr 2 Start/End (User 125) ,,,,"511402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Fr.2,Heating program 1 Fr 2 Start/End (User 125) ,,,,"5114",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#52 14
r,,HP1.Fr.3,Heating program 1 Fr 3 Start/End (User 125) ,,,,"521402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Fr.3,Heating program 1 Fr 3 Start/End (User 125) ,,,,"5214",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#60 14
r,,HP1.Sa.1,Heating program 1 Sa 1 Start/End (User 126) ,,,,"601402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Sa.1,Heating program 1 Sa 1 Start/End (User 126) ,,,,"6014",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#61 14
r,,HP1.Sa.2,Heating program 1 Sa 2 Start/End (User 126) ,,,,"611402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Sa.2,Heating program 1 Sa 2 Start/End (User 126) ,,,,"6114",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#62 14
r,,HP1.Sa.3,Heating program 1 Sa 3 Start/End (User 126) ,,,,"621402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Sa.3,Heating program 1 Sa 3 Start/End (User 126) ,,,,"6214",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#70 14
r,,HP1.Su.1,Heating program 1 Su 1 Start/End (User 127) ,,,,"701402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Su.1,Heating program 1 Su 1 Start/End (User 127) ,,,,"7014",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#71 14
r,,HP1.Su.2,Heating program 1 Su 2 Start/End (User 127) ,,,,"711402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Su.2,Heating program 1 Su 2 Start/End (User 127) ,,,,"7114",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,

#72 14
r,,HP1.Su.3,Heating program 1 Su 3 Start/End (User 127) ,,,,"721402",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,
w,,HP1.Su.3,Heating program 1 Su 3 Start/End (User 127) ,,,,"7214",,,_8_TimeStart,,, ,,,_8_TimeEnd,,,