# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
*r,,,,,,"5000",,,,,,,

#Ex-RAM 
r,,TWEICHEIST,Weichentemp B11 - Decouple Temp B11 ,,,,"98037c",,s,_8_Skip,,, ,,s,UCH,,,
r,,MODI_NGSOLL,cDrehzSoll - Speed Set ,,,,"3a03de",,s,_8_Skip,,, ,,s,UCH,,,
r,,Z_IondmueA,cIOIst - Io actual ,,,,"3103d5",,s,_8_Skip,,, ,,s,UCH,,,
r,,AIN_0_10V,0-10V N1 ,,,,"930377",,s,_8_Skip,,, ,,s,UCH,,,
r,,MODULATIONSGRAD,cModgrad - Modgrad ,,,,"5603B2",,s,_8_Skip,,, ,,s,UCH,,,