# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
*r,,,,,,"5000",,,,,,,

r,,HeatingSpecialist1,Heating Specialist ,,,,"dfb21b",,s,_8_Skip,,, ,P31,s,_8_Temp0,,, ,P30,s,_8_Temp0,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,P47,s,_8_Temp0K,,, ,P18,s,_8_Temp0,,, ,,s,UCH,,,,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,
r,,HeatingSpecialist2,Heating Specialist ,,,,"e3b227",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,
r,,HeatingSpecialist3,Heating Specialist ,,,,"f7b233",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,
r,,HeatingSpecialist4,Heating Specialist ,,,,"fbb23f",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,
r,,HeatingSpecialist5,Heating Specialist,,,,"ab624b02440237",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, 

r,,ProcessValues,Process values ,,,,"1a03b2012101250165016a",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,

#RAM 
r,,TVSOLL,cVL_Mod_Soll - Sup /Mod SetPoint ,,,,"32016e",,s,_8_Skip,,, ,,s,UCH,,,
r,,TVIST,cVLIstB12 - Sup. Act(NCT) B12 ,,,,"340168",,s,_8_Skip,,, ,,s,UCH,,,
r,,TRLIST,cRL_B13 - RL B13 ,,,,"3e0162",,s,_8_Skip,,, ,,s,UCH,,,
r,,TWWSOLL_HS,cWWSoll - cWWSolwert ,,,,"33016f",,s,_8_Skip,,, ,,s,UCH,,,
r,,TWWIST,cWWIstB3 - DHW Actual B3 ,,,,"36016a",,s,_8_Skip,,, ,,s,UCH,,,
r,,TABGAS,cTAbgas - Flue Gas Temp ,,,,"3f0163",,s,_8_Skip,,, ,,s,UCH,,,
r,,TAUSSEN,cTAussen - Outdoor Temp ,,,,"30016c",,s,_8_Skip,,, ,,s,UCH,,,
r,,TWEICHEIST,Weichentemp B11 - Decouple Temp B11 ,,,,"98037c",,s,_8_Skip,,, ,,s,UCH,,,
r,,MODI_NGSOLL,cDrehzSoll - Speed Set ,,,,"3a03de",,s,_8_Skip,,, ,,s,UCH,,,
r,,NGIST,cDrehzIst - Speed Act ,,,,"2b0177",,s,_8_Skip,,, ,,s,UCH,,,
r,,PUHZPWM,cPWMPumpe - PWM Pump ,,,,"b101ed",,s,_8_Skip,,, ,,s,UCH,,,
r,,Z_IondmueA,cIOIst - Io actual ,,,,"3103d5",,s,_8_Skip,,, ,,s,UCH,,,
r,,AIN_0_10V,0-10V N1 ,,,,"930377",,s,_8_Skip,,, ,,s,UCH,,,
r,,YPWM,cPWM_Fan - PWM Fan ,,,,"22017e",,s,_8_Skip,,, ,,s,UCH,,,
r,,EB_0000,GPS APS APS SIphon WPS H1 H2 ,,,,"7b0127",,s,_8_Skip,,, ,GDW,s,BI0,,,cGDW ,LDW,s,BI1,,,cLDW ,FS_IN_1,s,BI2,,,cLDW Siphon ,FS_IN_2,s,BI3,,,cWDW ,FS_IN_3,s,BI4,,,.H1 ,FS_IN_4,s,BI5,,,.H2 ,FL,s,BI6,,,Flame ,DREHZ_OK,s,BI7,,,
r,,AB_0000,MFA1 MFA2 VA Ignition Valve1 Valve2 Pump ,,,,"77012b",,s,_8_Skip,,, ,COMMON,s,BI0,,, ,ZUEND,s,BI1,,,cZuendung ,V1,s,BI2,,,cVentil1 ,V2,s,BI3,,,cVentil2 ,PROG_REL_1,s,BI4,,,.MFA1 ,PROG_REL_2,s,BI5,,,.MFA2 ,PUHZ,s,BI6,,,cPumpe ,PROG_REL_3,s,BI7,,,cVA 
r,,F_CODE,cStoerung - Lockout ,,,,"390165",,s,_8_Skip,,, ,,s,UCH,,,
r,,T_ESTB2,cVLIstSTB - Sup. Act. (eSTB),,,,"02015e",,s,_8_Skip,,, ,,s,UCH,,,
r,,MODULATIONSGRAD,cModgrad - Modgrad ,,,,"5603B2",,s,_8_Skip,,, ,,s,UCH,,,


# ROM
r,,RELEASE, ,,,,"df95ef",,s,_8_Skip,,, ,,s,STR*,,,
r,,BUILD_DATE, ,,,,"0635fa",,s,_8_Skip,,, ,,s,HDA:3,,, ,,s,_8_Day,,,
r,,CHKSUM, ,,,,"3e15fe",,s,_8_Skip,,, ,,s,HEX:2,,, 

