# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
*r,,,,,,"5000",,,,,,,

# ROM
r,,RELEASE, ,,,,"df95ef",,s,_8_Skip,,, ,,s,STR:10,,,
r,,BUILD_DATE, ,,,,"0635fa",,s,_8_Skip,,, ,,s,HDA:3,,, ,,s,_8_Day,,,
r,,CHKSUM, ,,,,"3e15fe",,s,_8_Skip,,, ,,s,HEX:2,,, 
