# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
*r,,,,,,"5000",,,,,,,

r,,Statistic1,Statistics ,,,,"a506031205",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,,
r,,Statistic2,Statistics ,,,,"a6060192d2",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, 
r,,Statistic3,Statistics ,,,,"a8060192dc",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, 
r,,Statistic4,Statistics ,,,,"bc060192c8",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, 
r,,Statistic5,Statistics ,,,,"c0060192b4",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, 
r,,Statistic6,Statistics ,,,,"ca060192be",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, 
r,,Statistic7,Statistics ,,,,"d4060192a0",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, 
r,,Statistic8,Statistics ,,,,"de060192aa",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, 
r,,Statistic9,Statistics ,,,,"e206019296",,s,_8_Skip,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,,  ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,, ,,s,UCH,,,,,s,UCH,,, 
